version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      # Check for updates to python packages every week
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/kotlin/gradle"
    schedule:
      # Check for updates to kotlin packages every week
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/rust/lambdas/courtdoc-anonymiser"
    schedule:
      interval: "weekly"