[package]
name = "testlib"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_fs = "1.1.3"
flate2 = "1.1.8"
serde_json = "1.0.149"
tar = "0.4.44"
