name: 'Deploy anonymiser lambda'
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: The environment to deploy against.
        type: choice
        options:
          - intg
          - staging
          - prod
        default: intg
permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - id: role-name
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh: 
            print(f"role-name={'${{ github.event.inputs.environment }}'.title()}DPGithubActionsDeployLambdaRole", file=fh)
        shell: python
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@0d00a56e021d460a2d2bb10b9d8f94f6693a71ad
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ steps.role-name.outputs.role-name }}
          aws-region: eu-west-2
          role-session-name: DeployLambda
      - name: Deploy to lambda
        run: |
          pip install cargo-lambda
          cargo lambda build --release -p lambda
          cargo lambda deploy --binary-name lambda intg-dr2-court-document-package-anonymiser
      - name: Send success message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@917201e254f112ff041b952dae76ef767cae7378
        with:
          message: ":white_check_mark: Service dr2-court-document-package-anonymiser updated in ${{ github.event.inputs.environment }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Update release branch
        run: |
          git branch -f release-${{ github.event.inputs.environment }} HEAD
          git push -f origin release-${{ github.event.inputs.environment }}
      - name: Send failure message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@917201e254f112ff041b952dae76ef767cae7378
        if: failure()
        with:
          message: ":warning: Build failed for dr2-court-document-package-anonymiser"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
